<?php
	if($_GET['module']=='home'){
		include("modul/home.php");
	}
	elseif($_GET['module']=='uangharian'){
		include("modul/mod_uangharian/uangharian.php");
	}
	elseif($_GET['module']=='admin_aplikasi'){
		include("modul/mod_admin/admin.php");
	}
	elseif($_GET['module']=='laporan'){
		include("modul/mod_laporan/laporan.php");
	}
	elseif($_GET['module']=='uangrepresentasi'){
		include("modul/mod_uangrepresentasi/uangrepresentasi.php");
	}
	elseif($_GET['module']=='biayapenginapan'){
		include("modul/mod_biayapenginapan/biayapenginapan.php");
	}
	elseif($_GET['module']=='biayarapat'){
		include("modul/mod_biayarapat/biayarapat.php");
	}
	elseif($_GET['module']=='biayakendaraan'){
		include("modul/mod_biayakendaraan/biayakendaraan.php");
	}
	elseif($_GET['module']=='biayataksi'){
		include("modul/mod_biayataksi/biayataksi.php");
	}
	elseif($_GET['module']=='kegiatan'){
		include("modul/mod_kegiatan/kegiatan.php");
	}
	elseif($_GET['module']=='pokja'){
		include("modul/mod_pokja/pokja.php");
	}	 
	elseif($_GET['module']=='pokjad'){
		include("modul/mod_pokjad/pokjad.php");
	}
	elseif($_GET['module']=='surattugas'){
		include("modul/mod_surattugas/surattugas.php");
	}
	elseif($_GET['module']=='pegbepergian'){
		include("modul/mod_pegbepergian/pegbepergian.php");
	}
	elseif($_GET['module']=='pstaf'){
		include("modul/mod_pstaf/pstaf.php");
	}
	elseif($_GET['module']=='pd'){
		include("modul/mod_pd/pd.php");
	}
	elseif($_GET['module']=='lappokja'){
		include("modul/mod_lappokja/lappokja.php");
	}
	elseif($_GET['module']=='lappokja'){
		include("modul/mod_lappokja/lappokja_b.php");
	}
	elseif($_GET['module']=='lapakhir'){
		include("modul/mod_lapakhir/lapakhir.php");
	}
	elseif($_GET['module']=='keluar'){
		session_destroy();
		header("location:index.php");
	}
	else{
		include("modul/404.php");
	}
?>